# The base image to use in the build.
# This is mandatory and must be the first command in the file.

FROM busybox:latest

# `Docker inspect` can be used to view image Labels.
LABEL version = "1.0"
LABEL author = "Nagendra Babu N"

CMD ["echo", "Welcome to Docker Lab"]
# Now go back to the tutorial and follow the commands